### ISSUE TITLE
Auto update fails sometimes and empties the OUI table

### ISSUE THREAD

**Issue by p4tpr0** [thatfrankwayne/TA_oui-lookup#1]
Hello,

I’m using TA_oui-lookup on 2 different Splunk enterprise install and on both of them, the file oui.csv got emptied by the update script.
Running the command with a system provided python3 seems to work, but running the command with python3 as provided by Splunk fails: 

```
$ /opt/splunk/bin/python3 /opt/splunk/etc/apps/TA_oui-lookup/bin/get-oui-table.py
URL error with "https://standards-oui.ieee.org": unknown url type: https
```

Also, allowing the command  `getouitable` to run from search yields to an «error 1» and an empty result

**Comment by thatfrankwayne** [comment]
Curiously, I get a 418 error when I try the Python code in my IDE. That’s an April Fool’s Day status code<https://en.wikipedia.org/wiki/Hyper_Text_Coffee_Pot_Control_Protocol>. That makes me suspect that something weird is happening at the IEEE server or load balancer.

When I run the code from my (Ubuntu 24.04) system Python (3.12.3), it works fine and then I get the 418 error. When I run it like you did using /opt/splunk/bin/python3, it fails with the same error as you got. However, that’s not how you should run Splunk’s Python. If you run it the “right way” -- /opt/splunk/bin/splunk cmd python3 /opt/splunk/etc/apps/TA_oui-lookup/bin/get-oui-table.py – it works fine sometimes or else it gets the 418 error.

My Splunk search head (9.3.1) has a complete list that was updated on the 28th automatically.

How long has this not been working? What version of Splunk are you running? I will look at this tomorrow some more.

**Comment by p4tpr0** [comment]
We are still running Splunk 9.1.1, but I think the real issue here is on IEEE’s side. Yesterday my first manual attempt retrieved the proper result but any other attempt yielded to an error.

A good workaround would be to add `override_if_empty=false` in your auto-update saved search, so that the list is not overwritten by an empty result in case IEEE’s web server refuse to deliver. 

Thanks for the `...bin/splunk cmd python3 ...` syntax, I was not aware of that (or forgot about it).

**Comment by thatfrankwayne** [comment]
I’ve contacted IEEE support and am waiting for an update. I agree that this seems to be an IEEE website problem, but still I should avoid writing an empty table if I get a bad response.

To fix that, I’ve made the change you recommended. I updated the version number for release to Splunkbase. You can get it here in the meantime.

**Comment by thatfrankwayne** [comment]
Version 1.2.2 has been uploaded to Splunkbase and is awaiting approval. I will follow up with the IEEE about the website problems, but I've done what I can for now.
